### PR TITLE
Minor modifications.

### PR DESCRIPTION
**Pull request by johnny-nohandle**
Modified.: Interface Listing
Added....: Individual client files to the tar in addition to the .ovpn
Added....: Non-persistent tunneling option

### CODE REVIEW

**Comment by themightyshiv** [comment]
Awesome! Thanks for the pull request. I'll look over it ASAP and get it added in, much appreciated.

**Comment by johnny-nohandle** [comment]
No problem!

**Comment by themightyshiv** [comment]
Sorry it took me forever to get to this. I changed the cosmetics around to match the format with the rest of the script and left the rest as is. I added your git info into the THANKS file, if you would like me to add your real name, website, twitter, etc. Just let me know and I can get that added in. Thanks again.

**Comment by johnny-nohandle** [comment]
No problem, glad you liked the additions.

**Pull request merged**
